package com.luisbarqueira.materialyoucompose.ui.theme

import androidx.compose.ui.graphics.Color

// MATERIAL 3 COLORS

val md_theme_light_primary = Color(0xFF006971)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF71f5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF002022)
val md_theme_light_secondary = Color(0xFF4a6365)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcce7ea)
val md_theme_light_onSecondaryContainer = Color(0xFF051f21)
val md_theme_light_tertiary = Color(0xFF505f7d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd6e2ff)
val md_theme_light_onTertiaryContainer = Color(0xFF0a1b36)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafcfc)
val md_theme_light_onBackground = Color(0xFF191c1c)
val md_theme_light_surface = Color(0xFFfafcfc)
val md_theme_light_onSurface = Color(0xFF191c1c)
val md_theme_light_surfaceVariant = Color(0xFFdae4e5)
val md_theme_light_onSurfaceVariant = Color(0xFF3f494a)
val md_theme_light_outline = Color(0xFF6f797a)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2e3131)
val md_theme_light_inversePrimary = Color(0xFF4dd9e5)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4dd9e5)
val md_theme_dark_onPrimary = Color(0xFF00363b)
val md_theme_dark_primaryContainer = Color(0xFF004f55)
val md_theme_dark_onPrimaryContainer = Color(0xFF71f5ff)
val md_theme_dark_secondary = Color(0xFFb1cbce)
val md_theme_dark_onSecondary = Color(0xFF1c3437)
val md_theme_dark_secondaryContainer = Color(0xFF324b4d)
val md_theme_dark_onSecondaryContainer = Color(0xFFcce7ea)
val md_theme_dark_tertiary = Color(0xFFb8c7ea)
val md_theme_dark_onTertiary = Color(0xFF21304c)
val md_theme_dark_tertiaryContainer = Color(0xFF384764)
val md_theme_dark_onTertiaryContainer = Color(0xFFd6e2ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1c)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1c)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF3f494a)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc8c9)
val md_theme_dark_outline = Color(0xFF899394)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1c)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)
val md_theme_dark_inversePrimary = Color(0xFF006971)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF006970)
val error = Color(0xFFba1b1b)



